/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserName = IDL.Text;
export const RoomCode = IDL.Nat;
export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : UserName,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'checkMatchmakingStatus' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'createRoom' : IDL.Func([UserName, RoomCode], [], []),
  'getRoomMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'joinRoom' : IDL.Func([UserName, IDL.Nat], [], []),
  'requestMatchmaking' : IDL.Func([RoomCode], [UserName], []),
  'sendMessage' : IDL.Func([RoomCode, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserName = IDL.Text;
  const RoomCode = IDL.Nat;
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : UserName,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'checkMatchmakingStatus' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'createRoom' : IDL.Func([UserName, RoomCode], [], []),
    'getRoomMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'joinRoom' : IDL.Func([UserName, IDL.Nat], [], []),
    'requestMatchmaking' : IDL.Func([RoomCode], [UserName], []),
    'sendMessage' : IDL.Func([RoomCode, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };